### ISSUE TITLE
用python编写网页更新提醒程序 - Cmj's Blog

### ISSUE THREAD

**Issue by cmj2002** [cmj2002/cmj2002.github.io#7]
https://blog.caomingjun.com/2021/09/29/%E7%94%A8python%E7%BC%96%E5%86%99%E7%BD%91%E9%A1%B5%E6%9B%B4%E6%96%B0%E6%8F%90%E9%86%92%E7%A8%8B%E5%BA%8F/ 

 本学期的很多课程依赖课程网页发布通知、课件、作业、OJ。因为不想每天手动上这堆网站查看更改，我用python写了一个程序来自动检测和提醒课程网站的更改。 这篇文章将讲一下如何订阅我已经写好的提醒服务、如何写一个自己的提醒服务。 代码将于近日开源，开源后会把链接放在文章内。

**Comment by cmj2002** [comment]
补充一点，注意把用于接受邮件的邮箱的垃圾拦截关掉

**Comment by OrangeX4** [comment]
妙啊, 而且博文也很详细
